# Generated by Django 2.2 on 2022-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_iteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteam',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
